
networks:
  training_network:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis_training
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./.scripts/redis/config/redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      - training_network

  redis-mock:
    image: redis
    container_name: redismock_training
    links:
      - "redis:redis"
    volumes:
      - ./.scripts/redis/init_data.sh:/init_data.sh
    command: sh -c "/init_data.sh && tail -f /dev/null"
    networks:
      - training_network

  postgres:
    image: postgres:latest
    container_name: postgres_training
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./.scripts/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - training_network
